package com.secure.books.models;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;

/**
 * This class represents the book entity (books to be sold)
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name="books")
public class Book {

    @Column(name="book_id")
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
    private Integer bookId;

    @NotBlank(message = "Book title cannot be blank")
    @Column(name="title")
    private String title;

    @NotBlank(message = "Author cannot be left blank")
    private String author;

    private String description;

    @Min(value = 1, message = "Price must be at least $1")
    private Double price;

    private Double cost;

    @Column(name = "seller_user")
    private String sellerUser;  // username who posted the book

    /**
     * Constructor for Creating a book object, id is auto generated by database
     * @param bookName
     * @param price
     * @param cost
     */
    public Book(String title, String author, String description, Double price, Double cost, String sellerUser) {
        this.title = title;
        this.author = author;
        this.description = description;
        this.price = price;
        this.cost = cost;
        this.sellerUser = sellerUser;
    }

}